apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pomerium.authenticate.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.authenticate.serviceAccountName" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: authenticate
  annotations:
{{- if .Values.annotations }}
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.authenticate.serviceAccount.annotations }}
  {{- range $key, $value := .Values.authenticate.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pomerium.authorize.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.authorize.serviceAccountName" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: authorize
  annotations:
{{- if .Values.annotations }}
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.authorize.serviceAccount.annotations }}
  {{- range $key, $value := .Values.authorize.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pomerium.cache.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.cache.serviceAccountName" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
  annotations:
{{- if .Values.annotations }}
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.cache.serviceAccount.annotations }}
  {{- range $key, $value := .Values.cache.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pomerium.proxy.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.proxy.serviceAccountName" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: proxy
  annotations:
{{- if .Values.annotations }}
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.proxy.serviceAccount.annotations }}
  {{- range $key, $value := .Values.proxy.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

{{ if .Values.operator.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pomerium.operator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.operator.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: operator
  annotations:
{{- if .Values.operator.deployment.annotations }}
  {{- range $key, $value := .Values.operator.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else if .Values.annotations }}
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end -}}